# Info
site_name: Meetix Informatie
site_url: 'https://info.meetix.nl/'
site_description: 'Meetix informatie'
site_author: 'MeetixMedia'

# Repo
repo_url: 'https://github.com/Meetix/Meetix-Informatie'
repo_name: 'Meetix/Meetix-Informatie'
edit_uri: 'https://github.com/Meetix/Meetix-Informatie/tree/main/docs'

# Copyright
copyright: Copyright &copy; 2019 - 2023 Meetix



#Config
site_name: Meetix informatie
theme:
  name: material

  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Donkere modus
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: ichte modus
#Navigeer
nav:
  - Welkom: index.md
  - Server regels:
    - Algemene regels: algemeneregels.md
    - Offroad voertuigen: offroad.md
  - Toetscombinaties: keybinds.md
# Extensions

markdown_extensions:
  - pymdownx.keys
